export class ColumnInfo {
  CONSTRAINT_CATALOG: string;
  CONSTRAINT_SCHEMA: string;
  CONSTRAINT_NAME: string;
  TABLE_CATALOG: string;
  TABLE_SCHEMA: string;
  TABLE_NAME: string;
  COLUMN_NAME: string;
  ORDINAL_POSITION: number;
  POSITION_IN_UNIQUE_CONSTRAINT: number;
  REFERENCED_TABLE_SCHEMA: number;
  REFERENCED_TABLE_NAME: string;
  REFERENCED_COLUMN_NAME: string;
}
